/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/creativeTheme.ts
 * Command: astryx theme build theme/creativeTheme.ts --out theme/creative.css
 * Generated: 2026-07-19T09:53:38.659Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Heading' {
  interface XDSHeadingLevelMap {
    '1': true;
    '2': true;
    '3': true;
    '4': true;
    '5': true;
    '6': true;
  }
}
