/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/creativeTheme.ts
 * Command: astryx theme build theme/creativeTheme.ts --out theme/creative.css
 * Generated: 2026-07-19T10:29:46.397Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const neutralIconRegistry: IconRegistry;
export declare const creativeTheme: DefinedTheme;
