/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/metaecomTheme.ts
 * Command: astryx theme build theme/metaecomTheme.ts --out theme/metaecom.css
 * Generated: 2026-07-19T13:39:56.305Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Heading' {
  interface XDSHeadingLevelMap {
    '1': true;
    '2': true;
    '3': true;
    '4': true;
    '5': true;
    '6': true;
  }
}
