/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/metaecomTheme.ts
 * Command: astryx theme build theme/metaecomTheme.ts --out theme/metaecom.css
 * Generated: 2026-07-19T18:05:49.752Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const neutralIconRegistry: IconRegistry;
export declare const metaecomTheme: DefinedTheme;
