/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/neutralTheme.ts
 * Command: astryx theme build theme/neutralTheme.ts --out theme/theme.css
 * Generated: 2026-07-19T12:44:52.301Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Heading' {
  interface XDSHeadingLevelMap {
    '1': true;
    '2': true;
    '3': true;
    '4': true;
    '5': true;
    '6': true;
  }
}

declare module '@astryxdesign/core/Badge' {
  interface XDSBadgeVariantMap {
    'gray': true;
  }
}
