/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/neutralTheme.ts
 * Command: astryx theme build theme/neutralTheme.ts --out theme/theme.css
 * Generated: 2026-07-14T17:03:59.065Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const neutralIconRegistry: IconRegistry;
export declare const neutralTheme: DefinedTheme;
